---- Setup using Oracle
DROP TABLE definitions;
DROP TABLE entries;
DROP TABLE users;

-- Entries Table
CREATE TABLE entries (
    entry_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    entry_name VARCHAR2(255) NOT NULL UNIQUE
);


-- Users Table
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username VARCHAR2(255) NOT NULL UNIQUE
);


-- Definitions Table
CREATE TABLE definitions (
    definition_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    definition_text CLOB NOT NULL,
    example_text CLOB,
    synonyms CLOB,
    time_since_upload VARCHAR2(50),
    time_in_days NUMBER,
    votes NUMBER,
    entry_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    FOREIGN KEY (entry_id) REFERENCES entries(entry_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

