---- Setup using Oracle
DROP TABLE DEFINITIONS;
DROP TABLE ENTRIES;
DROP TABLE USERS;

-- Entries Table
CREATE TABLE ENTRIES (
    ENTRY_NAME VARCHAR2(255) PRIMARY KEY
);

-- Users Table
CREATE TABLE USERS (
    USERNAME VARCHAR2(255) PRIMARY KEY
);

-- Definitions Table
CREATE TABLE DEFINITIONS (
    DEFINITION_ID     CHAR(64) PRIMARY KEY, -- hash column as primary key insures no duplicate definitions (at least not by the same user)
    DEFINITION_TEXT   CLOB NOT NULL,
    EXAMPLE_TEXT      CLOB,
    SYNONYMS          CLOB,
    TIME_SINCE_UPLOAD VARCHAR2(50),
    TIME_IN_DAYS      NUMBER,
    VOTES             NUMBER,
    ENTRY_NAME        VARCHAR2(255) NOT NULL,
    USERNAME          VARCHAR2(255) NOT NULL,
    FOREIGN KEY ( ENTRY_NAME )
        REFERENCES ENTRIES ( ENTRY_NAME ),
    FOREIGN KEY ( USERNAME )
        REFERENCES USERS ( USERNAME )
);