name: Weekly Python Script Run

on:
  schedule: # delete to disable workflow
    # * is a wildcard that matches any value
    # 0 0 * * 0 means every Sunday at midnight
    - cron: '0 0 * * 0'
  workflow_dispatch:  # enable manual runs


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Scra
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up Node.js
      uses: actions/setup-node@v2  # Use setup-node action to set up Node.js
      with:
        node-version: '16'  # Specify Node.js version 16

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r resources/requirements.txt  # Install dependencies if you have a requirements.txt file

    - name: Run main.py
      run: python main.py
